# Neden Numpy

In [2]:
a = [1,2,3,4]
b = [2,3,4,5]   #bunlar normal liste formunda
a + b           #bu sekilde listelerle matematiksel islemler yapmak cok mümkün degil.

[1, 2, 3, 4, 2, 3, 4, 5]

In [3]:
import numpy as np
a = np.array(a)     #burada yukaridaki listeleri numpy array formuna dönüstürüyoruz
b = np.array(b)     #array ile liste arasinda fark vardir; array sadece numeric degerler ile calisan vektörlerdir.
a * b               #numpy array ile matematiksel islemler mümkün olur.

array([ 2,  6, 12, 20])

In [4]:
type(a)

numpy.ndarray

In [5]:
np.array([3.14,4,2,13])

array([ 3.14,  4.  ,  2.  , 13.  ])

## Sifirdan array olusturma

In [6]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [7]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
np.full((3,5),8)

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

In [9]:
np.arange(0,31,5)

array([ 0,  5, 10, 15, 20, 25, 30])

In [10]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [11]:
np.random.normal(6,4,(3,3))

array([[ 3.32350413, 10.01055717,  8.24692361],
       [10.47636648,  0.24644682,  6.65299827],
       [10.2594934 ,  2.34193407,  8.21934771]])

In [12]:
np.random.randint(0,10,(3,3))

array([[7, 0, 4],
       [5, 9, 8],
       [3, 1, 1]])

## Numpy array özellikleri

* **ndim**: boyut sayisi
* **shape**: boyut bilgisi
* **size**: toplam eleman sayisi
* **dtype**: array veri tipi 

In [13]:
np.random.randint(10, size = 10)

array([6, 9, 0, 2, 9, 8, 8, 8, 8, 2])

In [14]:
a = np.random.randint(10, size = 10)

In [15]:
a.ndim

1

In [16]:
a.shape

(10,)

In [17]:
a.size

10

In [18]:
a.dtype

dtype('int64')

In [19]:
b = np.random.randint(10, size = (3,5))
b

array([[1, 6, 7, 8, 7],
       [0, 4, 5, 8, 5],
       [4, 7, 9, 5, 0]])

In [20]:
b.ndim

2

In [21]:
b.shape

(3, 5)

In [22]:
b.size

15

In [23]:
b.dtype

dtype('int64')

## Array yeniden sekillendirme (reshaping)

In [24]:
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [25]:
np.arange(1,13).reshape((3,4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [26]:
a = np.arange(1,13)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [27]:
a.ndim

1

In [28]:
b = a.reshape(1,12)
b

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [29]:
b.ndim

2

## Array birlestirme (Concatenation)

In [30]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [31]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [32]:
z = np.array([7,8,9])

In [33]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
#Iki boyutlu birlestirme

In [35]:
a = np.array([[1,2,3],[4,5,6]])

In [36]:
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [37]:
np.concatenate([a,a], axis= 0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [38]:
np.concatenate([a,a], axis= 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [39]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[3,4,5],[7,8,9]])

In [40]:
np.concatenate([a,b], axis= 0)

array([[1, 2, 3],
       [4, 5, 6],
       [3, 4, 5],
       [7, 8, 9]])

In [41]:
np.concatenate([a,b], axis= 1)

array([[1, 2, 3, 3, 4, 5],
       [4, 5, 6, 7, 8, 9]])

## Array ayirma (Splitting)

In [42]:
x = np.array([1,2,3,99,99,3,2,1])

In [43]:
np.split(x,[3,5])            # x'i 3. ve 5. noktalardan ayirir ve üc vektör elde eder

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [44]:
a,b,c = np.split(x,[3,5])

In [45]:
a

array([1, 2, 3])

In [46]:
b

array([99, 99])

In [47]:
c

array([3, 2, 1])

In [48]:
#Iki boyutlu ayirma

In [49]:
m = np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [50]:
np.vsplit(m,[2])   # np.vsplit() ; axis= 0 gibi davranir (satirda böler)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [51]:
ust,alt = np.vsplit(m,[2])

In [52]:
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [53]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [54]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [55]:
np.hsplit(m, [2])   #np.hsplit() ; axis= 1 gibi davranir (sütunda böler)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [56]:
sol,sag = np.hsplit(m,[2])

In [57]:
sol

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [58]:
sag

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

## Array siralama (Sorting)

In [59]:
v = np.array([2,1,4,3,5])
v

array([2, 1, 4, 3, 5])

In [60]:
np.sort(v)   #sort() fonk. numpy ile kullanilirken veri setinin yapisini bozmaz

array([1, 2, 3, 4, 5])

In [61]:
v

array([2, 1, 4, 3, 5])

In [62]:
#Iki boyutlu array siralama

In [63]:
m = np.random.normal(20,5,(3,3))
m

array([[22.28107076, 22.67518208, 23.6402654 ],
       [24.7092536 , 19.07879653, 20.67636012],
       [ 8.8432926 , 15.29611854, 24.30313367]])

In [64]:
np.sort(m, axis= 1)       #her satırın içindeki elemanlar küçükten büyüğe doğru sıralanır

array([[22.28107076, 22.67518208, 23.6402654 ],
       [19.07879653, 20.67636012, 24.7092536 ],
       [ 8.8432926 , 15.29611854, 24.30313367]])

In [65]:
np.sort(m, axis= 0)      #her sütunun içindeki elemanlar küçükten büyüğe doğru sıralanır

array([[ 8.8432926 , 15.29611854, 20.67636012],
       [22.28107076, 19.07879653, 23.6402654 ],
       [24.7092536 , 22.67518208, 24.30313367]])

## Index ile Elemanlara Erismek 

In [66]:
a = np.random.randint(10, size= 10)
a

array([1, 3, 2, 6, 4, 7, 6, 3, 4, 7])

In [67]:
a[-1]

7

In [68]:
a[-1] = 11      #son elemanin 11 ile degistirilmesi
a

array([ 1,  3,  2,  6,  4,  7,  6,  3,  4, 11])

In [69]:
#Iki boyutlu array icin elemanlara erisim

In [70]:
m = np.random.randint(10, size= (3,5))
m

array([[7, 2, 7, 2, 3],
       [4, 0, 4, 0, 8],
       [4, 8, 5, 0, 5]])

In [71]:
m[0,0]   

7

In [72]:
m[2,0] = 11       #2.satir, 0. index elemaninin 11 ile degistirilmesi
m

array([[ 7,  2,  7,  2,  3],
       [ 4,  0,  4,  0,  8],
       [11,  8,  5,  0,  5]])

## Array Alt Küme Islemleri (Slicing)

In [73]:
a = np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [74]:
a[0:3]

array([20, 21, 22])

In [75]:
a[:3]

array([20, 21, 22])

In [76]:
a[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [77]:
a[1::2]

array([21, 23, 25, 27, 29])

In [78]:
a[0::2]

array([20, 22, 24, 26, 28])

In [79]:
#Iki boyutlu Slice islemleri

In [80]:
m = np.random.randint(10, size= (5,5))
m

array([[5, 3, 0, 3, 4],
       [5, 7, 8, 0, 8],
       [3, 8, 4, 9, 2],
       [9, 4, 3, 7, 9],
       [4, 9, 5, 9, 1]])

In [81]:
m[:,0]       #0. indeksteki sütunu al

array([5, 5, 3, 9, 4])

In [82]:
m[:,1]

array([3, 7, 8, 4, 9])

In [83]:
m[:,0:2]    #2. indekse kadarki sütunlari al

array([[5, 3],
       [5, 7],
       [3, 8],
       [9, 4],
       [4, 9]])

In [84]:
m[0,:]      #0. indeksteki satiri al

array([5, 3, 0, 3, 4])

In [85]:
m[1,:]

array([5, 7, 8, 0, 8])

In [86]:
m[0:2,:]    #2. indekse kadarki satirlari al

array([[5, 3, 0, 3, 4],
       [5, 7, 8, 0, 8]])

In [87]:
m[1:3,0:2]    #1-3 index araligindaki satirlari sec, 0-2 indeksteki sütunlari al

array([[5, 7],
       [3, 8]])

## Alt Küme Üzerinde Islem Yapmak

In [88]:
a = np.random.randint(10, size= (5,5))
a

array([[6, 3, 1, 6, 2],
       [2, 2, 5, 3, 3],
       [5, 7, 6, 8, 9],
       [1, 2, 9, 9, 9],
       [3, 8, 0, 7, 5]])

In [89]:
alt_a = a[0:3,0:2]
alt_a

array([[6, 3],
       [2, 2],
       [5, 7]])

In [90]:
alt_a[0,0] = 9999
alt_a[1,1] = 8888
alt_a

array([[9999,    3],
       [   2, 8888],
       [   5,    7]])

In [91]:
a   #alt_a üzerinde yapilan islemler a üst kümesine de etki eder

array([[9999,    3,    1,    6,    2],
       [   2, 8888,    5,    3,    3],
       [   5,    7,    6,    8,    9],
       [   1,    2,    9,    9,    9],
       [   3,    8,    0,    7,    5]])

In [92]:
#alt küme üzerinde yapilan islemlerin üst kümeyi etkilemesini istemiyorsak; .copy() fonksiyonunu kullaniriz

In [93]:
m = np.random.randint(10, size= (5,5))
m

array([[2, 1, 3, 5, 8],
       [6, 9, 3, 2, 3],
       [0, 3, 8, 0, 6],
       [6, 2, 6, 1, 5],
       [1, 1, 9, 8, 9]])

In [94]:
alt_m = m[0:3,0:2].copy()   #burada alt küme ile üst küme iliskisi kesilmistir
alt_m

array([[2, 1],
       [6, 9],
       [0, 3]])

In [95]:
alt_m[0,0] = 9999
alt_m

array([[9999,    1],
       [   6,    9],
       [   0,    3]])

In [96]:
m    #görüldügü gibi üst kümede herhangi bir degisiklik olmadi

array([[2, 1, 3, 5, 8],
       [6, 9, 3, 2, 3],
       [0, 3, 8, 0, 6],
       [6, 2, 6, 1, 5],
       [1, 1, 9, 8, 9]])

## Fancy Index ile Elemanlara Erismek

In [97]:
v = np.arange(0,30,3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [98]:
v[1]

3

In [99]:
v[3]

9

In [100]:
v[5]

15

In [101]:
[v[1],v[3],v[5]]  #ayri ayri olan verileri bir arada getirme

[3, 9, 15]

> yukaridaki islemleri ayri ayri index numaralarini her defasinda yazip v vektörünün icindeki degerlere ulasmak yerine, 
al_getir adinda bir liste olusturup bu listenin icine v vektöründe ulasmak istedigimiz index numaralarini birer eleman olarak yaziyoruz. 
sonra v[al_getir] komutuyla bütün ulasmak istedigimiz degerlere ulasiyoruz.
Bu islemlere Fancy Index denir.

In [102]:
al_getir = [1,3,5]

In [103]:
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [104]:
v[al_getir]    #Fancy Index Islemi  (Vektor boyutunda)

array([ 3,  9, 15])

In [105]:
#Iki boyutlu array icin Fancy Index islemi

In [106]:
m = np.arange(9).reshape((3,3))
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [107]:
satir = np.array([0,1])            #0. satirda 1. sütundaki eleman = 1 
sutun = np.array([1,2])            #1. satirda 2. sütundaki eleman = 5

In [108]:
m[satir,sutun]

array([1, 5])

In [109]:
#Basit index ile Fancy index

In [110]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [111]:
m[0,[1,2]]   #Fancy index ile basit index bir arada

array([1, 2])

In [112]:
#Slice ile Fancy Index bir arada

In [113]:
m[0:,[1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])

## Kosullu Eleman Islemleri

In [114]:
v = np.array([1,2,3,4,5])

In [115]:
v < 3

array([ True,  True, False, False, False])

In [116]:
v[v < 3]    #Fancy Index

array([1, 2])

In [117]:
v * 2

array([ 2,  4,  6,  8, 10])

## Matematiksel Islemler

In [118]:
v = np.array([1,2,3,4,5])

In [119]:
v - 1

array([0, 1, 2, 3, 4])

In [120]:
v * 5 

array([ 5, 10, 15, 20, 25])

> ufunc mekanizmasi ile arka plandaki matematiksel islemler su sekilde calistiriliyor;

In [121]:
np.subtract(v,1)    #cikarma islemi

array([0, 1, 2, 3, 4])

In [122]:
np.add(v,1)     #toplama islemi

array([2, 3, 4, 5, 6])

In [123]:
np.multiply(v,4)      #carpma islemi

array([ 4,  8, 12, 16, 20])

*Google üzerinden "Numpy mathematics cheat sheet" yazarak toplu olarak bütün islemlere ulasmak mümkün.

## NumPy ile Iki Bilinmeyenli Denklem Cözümü

5 * x0 + x1 = 12 

x0 + 3 * x1 = 10

In [124]:
a = np.array([[5,1],[1,3]])
b = np.array([12,10])

In [125]:
a

array([[5, 1],
       [1, 3]])

In [126]:
b

array([12, 10])

In [127]:
x = np.linalg.solve(a, b)
x

array([1.85714286, 2.71428571])