# Neden Numpy

In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
a = [1,2,3,4]
b = [2,3,4,5]
a + b           # listelerle  kisitli  matematiksel islemler yapilir.

[1, 2, 3, 4, 2, 3, 4, 5]

In [3]:
import numpy as np
a = np.array(a)
b = np.array(b)
a * b               #numpy array ile bütün matematiksel islemler mümkün olur.

array([ 2,  6, 12, 20])

In [4]:
type(a)

numpy.ndarray

In [5]:
np.array([3.14,4,2,13])

array([ 3.14,  4.  ,  2.  , 13.  ])

## Array olusturma

In [6]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [7]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
np.full((3,5),8)

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

In [9]:
np.arange(0,31,5)

array([ 0,  5, 10, 15, 20, 25, 30])

In [10]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [11]:
np.random.normal(6,4,(3,3))

array([[ 8.45355108, 10.06016503,  3.67029937],
       [ 3.86455654,  4.61358907,  3.94671943],
       [ 5.47501045,  4.97875348,  6.93721537]])

In [12]:
np.random.randint(0,10,(3,3))

array([[9, 7, 6],
       [6, 9, 6],
       [5, 6, 1]])

## Numpy Array özellikleri

* **ndim**: boyut sayisi
* **shape**: boyut bilgisi
* **size**: toplam eleman sayisi
* **dtype**: array veri tipi 

In [13]:
np.random.randint(10, size = 10)

array([8, 6, 1, 8, 6, 1, 3, 9, 0, 4])

In [14]:
a = np.random.randint(10, size = 10)

In [15]:
a.ndim

1

In [16]:
a.shape

(10,)

In [17]:
a.size

10

In [18]:
a.dtype

dtype('int64')

In [19]:
b = np.random.randint(10, size = (3,5))
b

array([[2, 8, 4, 2, 5],
       [5, 0, 1, 2, 5],
       [6, 2, 2, 8, 7]])

In [20]:
b.ndim

2

In [21]:
b.shape

(3, 5)

In [22]:
b.size

15

In [23]:
b.dtype

dtype('int64')

## Array yeniden sekillendirme (reshaping)

In [24]:
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [25]:
np.arange(1,13).reshape((3,4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [26]:
a = np.arange(1,13)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [27]:
a.ndim

1

In [28]:
b = a.reshape(1,12)
b

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [29]:
b.ndim

2

## Array birlestirme (Concatenation)

In [30]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [31]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [32]:
z = np.array([7,8,9])

In [33]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
#Iki boyutlu birlestirme

In [35]:
a = np.array([[1,2,3],[4,5,6]])

In [36]:
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [37]:
np.concatenate([a,a], axis= 0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [38]:
np.concatenate([a,a], axis= 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [39]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[3,4,5],[7,8,9]])

In [40]:
np.concatenate([a,b], axis= 0)

array([[1, 2, 3],
       [4, 5, 6],
       [3, 4, 5],
       [7, 8, 9]])

In [41]:
np.concatenate([a,b], axis= 1)

array([[1, 2, 3, 3, 4, 5],
       [4, 5, 6, 7, 8, 9]])

## Array ayirma (Splitting)

In [42]:
x = np.array([1,2,3,99,99,3,2,1])

In [43]:
np.split(x,[3,5])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [44]:
a,b,c = np.split(x,[3,5])

In [45]:
a

array([1, 2, 3])

In [46]:
b

array([99, 99])

In [47]:
c

array([3, 2, 1])

In [48]:
#Iki boyutlu ayirma
m = np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [49]:
np.vsplit(m,[2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [50]:
ust,alt = np.vsplit(m,[2])

In [51]:
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [52]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [53]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [54]:
np.hsplit(m, [2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [55]:
sol,sag = np.hsplit(m,[2])

In [56]:
sol

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [57]:
sag

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

## Array siralama (Sorting)

In [58]:
v = np.array([2,1,4,3,5])
v

array([2, 1, 4, 3, 5])

In [59]:
np.sort(v)   #sort() fonk. numpy ile kullanilirken veri setinin yapisini bozmaz

array([1, 2, 3, 4, 5])

In [60]:
v

array([2, 1, 4, 3, 5])

In [61]:
#Iki boyutlu array siralama
m = np.random.normal(20,5,(3,3))
m

array([[21.55522053, 21.93156992, 25.71018016],
       [13.39177008, 12.15298836, 18.8478825 ],
       [24.02979571, 22.73616726, 15.78472175]])

In [62]:
np.sort(m, axis= 1)

array([[21.55522053, 21.93156992, 25.71018016],
       [12.15298836, 13.39177008, 18.8478825 ],
       [15.78472175, 22.73616726, 24.02979571]])

In [63]:
np.sort(m, axis= 0)

array([[13.39177008, 12.15298836, 15.78472175],
       [21.55522053, 21.93156992, 18.8478825 ],
       [24.02979571, 22.73616726, 25.71018016]])

## Index ile Elemanlara Erismek 

In [64]:
a = np.random.randint(10, size= 10)
a

array([1, 5, 1, 5, 5, 3, 6, 2, 2, 3])

In [65]:
a[-1]

3

In [66]:
a[-1] = 11
a

array([ 1,  5,  1,  5,  5,  3,  6,  2,  2, 11])

In [67]:
m = np.random.randint(10, size= (3,5))
m

array([[3, 9, 5, 1, 0],
       [6, 2, 4, 5, 0],
       [4, 8, 0, 5, 1]])

In [68]:
m[0,0]   

3

In [69]:
m[2,0] = 11
m

array([[ 3,  9,  5,  1,  0],
       [ 6,  2,  4,  5,  0],
       [11,  8,  0,  5,  1]])

## Array Alt Küme Islemleri (Slicing)

In [70]:
a = np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [71]:
a[0:3]

array([20, 21, 22])

In [72]:
a[:3]

array([20, 21, 22])

In [73]:
a[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [74]:
a[1::2]

array([21, 23, 25, 27, 29])

In [75]:
a[0::2]

array([20, 22, 24, 26, 28])

In [76]:
#Iki boyutlu Slicing siralama
m = np.random.randint(10, size= (5,5))
m

array([[7, 4, 4, 2, 7],
       [2, 2, 7, 3, 6],
       [6, 9, 1, 9, 5],
       [7, 4, 5, 6, 0],
       [8, 2, 2, 7, 7]])

In [77]:
m[:,0]

array([7, 2, 6, 7, 8])

In [78]:
m[:,1]

array([4, 2, 9, 4, 2])

In [79]:
m[:,0:2]

array([[7, 4],
       [2, 2],
       [6, 9],
       [7, 4],
       [8, 2]])

In [80]:
m[0,:]

array([7, 4, 4, 2, 7])

In [81]:
m[1,:]

array([2, 2, 7, 3, 6])

In [82]:
m[0:2,:]

array([[7, 4, 4, 2, 7],
       [2, 2, 7, 3, 6]])

In [83]:
m[1:3,0:2]

array([[2, 2],
       [6, 9]])

## Alt Küme Üzerinde Islem Yapmak

In [84]:
a = np.random.randint(10, size= (5,5))
a

array([[0, 8, 1, 7, 3],
       [5, 1, 8, 7, 4],
       [8, 8, 0, 8, 0],
       [7, 0, 2, 2, 3],
       [2, 6, 3, 0, 1]])

In [85]:
alt_a = a[0:3,0:2]
alt_a

array([[0, 8],
       [5, 1],
       [8, 8]])

In [86]:
alt_a[0,0] = 9999
alt_a[1,1] = 8888
alt_a

array([[9999,    8],
       [   5, 8888],
       [   8,    8]])

In [87]:
a

array([[9999,    8,    1,    7,    3],
       [   5, 8888,    8,    7,    4],
       [   8,    8,    0,    8,    0],
       [   7,    0,    2,    2,    3],
       [   2,    6,    3,    0,    1]])

In [88]:
#alt küme üzerinde yapilan islemlerin üst kümeyi etkilemesini istemiyorsak; .copy() fonksiyonunu kullaniriz

In [89]:
m = np.random.randint(10, size= (5,5))
m

array([[3, 2, 1, 9, 7],
       [1, 3, 0, 8, 3],
       [9, 0, 8, 8, 0],
       [4, 4, 1, 6, 6],
       [6, 3, 5, 4, 0]])

In [90]:
alt_m = m[0:3,0:2].copy()   #burada alt küme ile üst küme iliskisi kesilmistir
alt_m

array([[3, 2],
       [1, 3],
       [9, 0]])

In [91]:
alt_m[0,0] = 9999
alt_m

array([[9999,    2],
       [   1,    3],
       [   9,    0]])

In [92]:
m

array([[3, 2, 1, 9, 7],
       [1, 3, 0, 8, 3],
       [9, 0, 8, 8, 0],
       [4, 4, 1, 6, 6],
       [6, 3, 5, 4, 0]])

## Fancy Index ile Elemanlara Erismek

In [93]:
v = np.arange(0,30,3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [94]:
v[1]

3

In [95]:
v[3]

9

In [96]:
v[5]

15

In [97]:
[v[1],v[3],v[5]]

[3, 9, 15]

In [98]:
al_getir = [1,3,5]

In [99]:
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [100]:
v[al_getir]

array([ 3,  9, 15])

In [101]:
m = np.arange(9).reshape((3,3))
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [102]:
satir = np.array([0,1])
sutun = np.array([1,2])

In [103]:
m[satir,sutun]

array([1, 5])

In [104]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [105]:
m[0,[1,2]]

array([1, 2])

In [106]:
#Slice & Fancy Index

In [107]:
m[0:,[1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])

## Kosullu Eleman Islemleri

In [108]:
v = np.array([1,2,3,4,5])

In [109]:
v < 3

array([ True,  True, False, False, False])

In [110]:
v[v < 3]    #Fancy Index

array([1, 2])

In [111]:
v * 2

array([ 2,  4,  6,  8, 10])

## Matematiksel Islemler

In [112]:
v = np.array([1,2,3,4,5])

In [113]:
v - 1

array([0, 1, 2, 3, 4])

In [114]:
v * 5 

array([ 5, 10, 15, 20, 25])

> ufunc

In [115]:
np.subtract(v,1)    #cikarma islemi

array([0, 1, 2, 3, 4])

In [116]:
np.add(v,1)     #toplama islemi

array([2, 3, 4, 5, 6])

In [117]:
np.multiply(v,4)      #carpma islemi

array([ 4,  8, 12, 16, 20])

*Google üzerinden "Numpy mathematics cheat sheet" yazarak toplu olarak bütün islemlere ulasmak mümkün.

## NumPy ile Iki Bilinmeyenli Denklem Cözümü

5 * x0 + x1 = 12 

x0 + 3 * x1 = 10

In [118]:
a = np.array([[5,1],[1,3]])
b = np.array([12,10])

In [119]:
a

array([[5, 1],
       [1, 3]])

In [120]:
b

array([12, 10])

In [121]:
x = np.linalg.solve(a, b)
x

array([1.85714286, 2.71428571])